---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: v1.15.8
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  values:
    crds:
      enabled: true

    csi:
      enableVolumeGroupSnapshot: false # TODO: enable this when v1beta1 CRDs are available
      kubeletDirPath: /var/lib/kubelet
      enableCSIHostNetwork: true
      pluginTolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"

    monitoring:
      enabled: true

    resources:
      requests:
        cpu: 109m
        memory: 204M
      limits:
        memory: 453M
