---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: atuin-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        ATUIN_DB_URI: |-
          postgres://{{ .pg_username }}:{{ .pg_password }}@postgres.database.svc.cluster.local/atuin
        # Postgres Init
        INIT_POSTGRES_DBNAME: atuin
        INIT_POSTGRES_HOST: postgres.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .pg_username }}"
        INIT_POSTGRES_PASS: "{{ .pg_password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: atuin
    - extract:
        key: zalando-postgres
