---
area/ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
area/cluster:
  - changed-files:
      - any-glob-to-any-file:
          - "k8s/global/**/*"
          - "k8s/clusters/**/*"
          - "k8s/manifests/**/*"
area/docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**/*"
area/os:
  - changed-files:
      - any-glob-to-any-file: "k8s/talos/**/*"
