---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piper-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 2Gi
