---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minio-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MINIO_ROOT_USER: "{{ .minio_accesskey }}"
        MINIO_ROOT_PASSWORD: "{{ .minio_secretkey }}"
  dataFrom:
    - extract:
        # MINIO_ROOT_USER, MINIO_ROOT_PASSWORD
        key: minio
