---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: downloads-gateway
  namespace: vpn
spec:
  interval: 15m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: angelnu-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.12.0@sha256:8b35b9ebe2be4dfdce44934e298ab196bc59dd2a47ec5f62423e6b573ae94a6b

    DNS: 172.16.1.1

    addons:
      vpn:
        enabled: true
        type: gluetun
        image:
          repository: docker.io/qmcgaw/gluetun
          tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
        env:
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"
          - name: TZ
            value: ${TIMEZONE}
          - name: WIREGUARD_PRESHARED_KEY
            value: ""

        envFrom:
          - secretRef:
              name: vpn-config
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

        # networkPolicy:
        #   enabled: true
        #   egress:
        #     - to:
        #         - ipBlock:
        #             cidr: 0.0.0.0/0
        #       ports:
        #         # VPN traffic
        #         - port: 51820
        #           protocol: UDP
        #     - to:
        #         - ipBlock:
        #             cidr: 10.0.0.0/8

      netshoot:
        enabled: true
        resources:
          requests:
            cpu: 5m
            memory: 10M
          limits:
            memory: 10M

    podAnnotations:
      configmap.reloader.stakater.com/reload: downloads-gateway-pod-gateway
      secret.reloader.stakater.com/reload: downloads-gateway-vpnconfig

    publicPorts:
      - hostname: qbittorrent #hostname assigned to the pod
        IP: 10 # must be an integer between 2 and VXLAN_GATEWAY_FIRST_DYNAMIC_IP (20 by default)
        ports:
          - type: udp
            port: 57847
          - type: tcp
            port: 57847

    routed_namespaces:
      - downloads

    settings:
      VPN_INTERFACE: wg0
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1
      VXLAN_GATEWAY_FIRST_DYNAMIC_IP: 20
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_TRAFFIC_PORT: "51820"
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16

    webhook:
      gatewayAnnotation: setDownloadGateway
      gatewayDefault: false
      gatewayLabel: setDownloadGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.10.0@sha256:a8ed630613de277244dfe203cd11d05905d7eeba8d8c41e399b02ee9a847b2f5
