# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: node-red-nfs-config
# spec:
#   storageClassName: node-red-nfs-config
#   capacity:
#     storage: 1Mi
#   accessModes:
#     - ReadWriteMany
#   nfs:
#     path: /mnt/fatguys/k8s/node-red
#     server: ${SECRET_NAS1}
#   mountOptions:
#     - nfsvers=4.1
#     - tcp
#     - hard
#     - noatime
#     - nodiratime
#     - rsize=1048576
#     - wsize=1048576

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-config
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
