---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${rsrc}-${claim}-${ts}"
  namespace: "${namespace}"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "${rsrc}-restic-secret"
    destinationPVC: "${claim}"
    copyMethod: Direct
    storageClassName: ceph-block
    # Restore from the Nth most recent snapshot (1 = latest, 2 = second-to-last, etc.)
    previous: $snapshot
    moverSecurityContext:
      runAsUser: 10000
      runAsGroup: 10000
      fsGroup: 10000
