---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: esphome-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secrets.yaml: |-
          wifi_ssid: "{{ .wifi_ssid }}"
          wifi_password: "{{ .wifi_password }}"

          ota_password: "{{ .ota_password }}"
  dataFrom:
    - extract:
        key: esphome
