---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name lubelog-secret
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      data:
        # app
        POSTGRES_CONNECTION: "Host=postgres.database.svc.cluster.local:5432;Username={{ .POSTRES_USER }};Password={{ .POSTGRES_PASS }};Database=lubelog"
        # # OIDC
        # OpenIDConfig__Name: authentik
        # OpenIDConfig__ClientId: "{{ .LUBELOG_CLIENT_ID }}"
        # OpenIDConfig__ClientSecret: "{{ .LUBELOG_CLIENT_SECRET }}"
        # OpenIDConfig__AuthURL: https://sso.${SECRET_DOMAIN}/application/o/authorize/
        # OpenIDConfig__TokenURL: https://sso.${SECRET_DOMAIN}/application/o/token/
        # OpenIDConfig__RedirectURL: https://lubelog.${SECRET_DOMAIN}/Login/RemoteAuth
        # OpenIDConfig__Scope: email
        # Database init
        INIT_POSTGRES_DBNAME: lubelog
        INIT_POSTGRES_HOST: postgres.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: lubelog
    - extract:
        key: zalando-postgres
