---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  namespace: kube-system
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect.${SECRET_DOMAIN}
      vaults:
        k8s: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-secret
            key: token
            namespace: kube-system
