---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      version: 0.8.2
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs
        namespace: flux-system
      interval: 5m
  values:
    image:
      # repository: raspbernetes/node-feature-discovery
      # tag: "v0.8.1"
      pullPolicy: IfNotPresent
    master:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values: [""]
    # node-feature-discovery configuration - see https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/nfd-worker.conf.example for example
    worker:
      config: |-
        core:
          sources:
          - custom
          - pci
          - usb
        sources:
          usb:
            deviceClassWhitelist:
            - "02"
            - "03"
            - "0e"
            - "ef"
            - "fe"
            - "ff"
            deviceLabelFields:
            - "class"
            - "vendor"
            - "device"
          custom:
          - name: "zigbee"
            matchOn:
            - usbId:
              class: ["ff"]
              vendor: ["1a86"]
              device: ["7523"]
          - name: "zwave"
            matchOn:
            - usbId:
              class: ["02"]
              vendor: ["0658"]
              device: ["0200"]
          - name: "cyberpower-ups"
            matchOn:
            - usbId:
              class: ["00"]
              vendor: ["0746"]
              device: ["0501"]
          - name: "3dprinter-mpsm"
            matchOn:
            - usbId:
              class: ["02"]
              vendor: ["2974"]
              device: ["0503"]
          - name: "3dprinter-ender"
            matchOn:
            - usbId:
              class: ["02"]
              vendor: ["1eaf"]
              device: ["0004"]
          - name: "webcam-c270"
            matchOn:
            - usbId:
              class: ["ef"]
              vendor: ["046d"]
              device: ["0825"]
      tolerations:
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"
