---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        DB_DATABASE_NAME: &dbName immich
        DB_HOSTNAME: &dbHost postgres.database.svc.cluster.local
        DB_USERNAME: &dbUser "{{ .DB_USERNAME }}"
        DB_PASSWORD: &dbPass "{{ .DB_PASSWORD }}"
        REDIS_PASSWORD: "{{ .REDIS_PASSWORD }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        TYPESENSE_API_KEY: "{{ .TYPESENSE_API_KEY }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: zalando-postgres
