---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent-config
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbittorrent-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # qBittorrent
        MAM_ID: "{{ .MAM_ID }}"
        MAM_URL: "{{ .MAM_URL }}"

        # VPN
        VPN_SERVICE_PROVIDER: "{{ .VPN_SERVICE_PROVIDER }}"
        VPN_TYPE: "{{ .VPN_TYPE }}"
        WIREGUARD_ENDPOINT_IP: "{{ .VPN_ENDPOINT_IP }}"
        WIREGUARD_ENDPOINT_PORT: "{{ .VPN_ENDPOINT_PORT }}"
        WIREGUARD_PUBLIC_KEY: "{{ .WIREGUARD_PUBLIC_KEY }}"
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        # WIREGUARD_PRESHARED_KEY: "{{ .WIREGUARD_PRESHARED_KEY }}"
        WIREGUARD_ADDRESSES: "{{ .WIREGUARD_ADDRESSES }}"
        DNS_ADDRESS: "{{ .DNS_ADDRESS }}"
  dataFrom:
    - extract:
        key: qbittorrent
    - extract:
        key: vpn-gateway
