---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
