---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://bjw-s-labs.github.io/helm-charts
  timeout: 2m
