---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/fluxcd/flux-manifests
  ref:
    tag: v2.6.2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m
  path: ./
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: flux-manifests
  patches:
    - patch: |
        $patch: delete
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: not-used
      target:
        group: networking.k8s.io
        version: v1
        kind: NetworkPolicy
    - patch: |
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --concurrent=8
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --kube-api-qps=500
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --kube-api-burst=1000
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --requeue-dependency=5s
      target:
        kind: Deployment
        name: "(kustomize-controller|helm-controller|source-controller)"
    - patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: not-used
        spec:
          template:
            spec:
              containers:
                - name: manager
                  resources:
                    limits:
                      memory: 2Gi
      target:
        kind: Deployment
        name: "(kustomize-controller|helm-controller|source-controller)"
    - patch: |
        - op: add
          path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/eventSources/items/properties/kind/enum/-
          value: Terraform
      target:
        kind: CustomResourceDefinition
        name: alerts.notification.toolkit.fluxcd.io
    - patch: |
        - op: add
          path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/resources/items/properties/kind/enum/-
          value: Terraform
      target:
        kind: CustomResourceDefinition
        name: receivers.notification.toolkit.fluxcd.io
    - patch: |
        - op: add
          path: /rules/-
          value:
            apiGroups: ["infra.contrib.fluxcd.io"]
            resources: ["*"]
            verbs: ["*"]
      target:
        kind: ClusterRole
        name: crd-controller-flux-system

    # GCP KMS: https://github.com/fluxcd/kustomize-controller/blob/5056fbf6ac5c48de434680042c5979fa79a5de04/docs/spec/v1beta2/kustomization.md#gcp-kms
    - target:
        kind: Deployment
        name: kustomize-controller
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/gcp/gcp-flux-sa-credential.json
        - op: add
          path: /spec/template/spec/containers/0/volumeMounts/-
          value:
            mountPath: /var/gcp/gcp-flux-sa-credential.json
            name: fluxcd-google-sa-secret
            subPath: gcp-flux-sa-credential.json
            readOnly: true
        - op: add
          path: /spec/template/spec/volumes/-
          value:
            name: fluxcd-google-sa-secret
            secret:
              secretName: fluxcd-google-sa-secret
