---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-restic
  namespace: system-monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .REPOSITORY_TEMPLATE }}/grafana"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync-restic-template
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: grafana
  namespace: system-monitoring
spec:
  sourcePVC: grafana-config
  trigger:
    schedule: "0 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: grafana-restic-secret
    cacheCapacity: 8Gi
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 472
      runAsGroup: 472
      fsGroup: 472
    retain:
      daily: 14
