---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-namespace
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/system"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: system-kyverno
#   namespace: flux-system
# spec:
#   interval: 5m
#   path: "./k8s/clusters/cluster-0/manifests/system/kyverno"
#   prune: false
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-gitops
# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: GitRepository
# metadata:
#   name: system-kyverno-git
#   namespace: flux-system
# spec:
#   interval: 12h
#   url: https://github.com/kyverno/kyverno.git
#   ref:
#     # renovate: registryUrl=https://kyverno.github.io/kyverno chart=kyverno
#     tag: kyverno-chart-3.4.1
#   ignore: |
#     # exclude all
#     /*
#     # include crd directory
#     !/config/crds
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: system-kyverno-crds
#   namespace: flux-system
# spec:
#   interval: 30m
#   prune: false
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: system-kyverno-git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-reloader
  namespace: flux-system
spec:
  dependsOn:
    - name: system-namespace
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/system/reloader"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops

# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: system-descheduler
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: system-namespace
#   interval: 5m
#   path: "./k8s/clusters/cluster-0/manifests/system/descheduler"
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-gitops
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: system-kyverno-base
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: system-namespace
#   interval: 5m
#   path: "./k8s/clusters/cluster-0/manifests/system/kyverno/base"
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-gitops
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: system-kyverno-policies
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: system-namespace
#   interval: 5m
#   path: "./k8s/clusters/cluster-0/manifests/system/kyverno/policies"
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-volsync
  namespace: flux-system
spec:
  dependsOn:
    - name: system-namespace
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/system/volsync"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-democratic-csi-local-path
  namespace: flux-system
spec:
  dependsOn:
    - name: system-namespace
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/system/democratic-csi/local-path"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
