---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-monitoring-namespace
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/system-monitoring"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-monitoring-kube-prom-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: system-monitoring-namespace
    - name: rook-ceph-cluster
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/system-monitoring/kube-prometheus-stack"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-monitoring-thanos
  namespace: flux-system
spec:
  dependsOn:
    - name: system-monitoring-namespace
    - name: rook-ceph-cluster
    # - name: selfhosted-minio
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/system-monitoring/thanos"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: system-monitoring-botkube
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: system-monitoring-namespace
#     - name: system-monitoring-kube-prom-stack
#   interval: 5m
#   path: "./k8s/clusters/cluster-0/manifests/system-monitoring/botkube"
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-monitoring-grafana
  namespace: flux-system
spec:
  dependsOn:
    - name: system-monitoring-namespace
    - name: system-monitoring-kube-prom-stack
    - name: rook-ceph-cluster
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/system-monitoring/grafana"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: system-monitoring-vector-aggregator
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: system-monitoring-namespace
#     - name: system-monitoring-kube-prom-stack
#   interval: 5m
#   path: "./k8s/clusters/cluster-0/manifests/system-monitoring/vector/aggregator"
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-gitops
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: system-monitoring-vector-agent
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: system-monitoring-namespace
#     - name: system-monitoring-kube-prom-stack
#     - name: system-monitoring-vector-aggregator
#   interval: 5m
#   path: "./k8s/clusters/cluster-0/manifests/system-monitoring/vector/agent"
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-gitops
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: system-monitoring-loki
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: system-monitoring-namespace
#     - name: system-monitoring-kube-prom-stack
#     - name: rook-ceph-cluster
#   interval: 5m
#   path: "./k8s/clusters/cluster-0/manifests/system-monitoring/loki"
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-monitoring-speedtest-exporter
  namespace: flux-system
spec:
  dependsOn:
    - name: system-monitoring-namespace
    - name: system-monitoring-kube-prom-stack
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/system-monitoring/speedtest-exporter"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-monitoring-prometheus-smartctl
  namespace: flux-system
spec:
  dependsOn:
    - name: system-monitoring-namespace
    - name: system-monitoring-kube-prom-stack
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/system-monitoring/prometheus-smartctl"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-monitoring-vpa
  namespace: flux-system
spec:
  dependsOn:
    - name: system-monitoring-namespace
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/system-monitoring/vpa"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: system-monitoring-goldilocks
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: system-monitoring-namespace
#     - name: system-monitoring-vpa
#   interval: 5m
#   path: "./k8s/clusters/cluster-0/manifests/system-monitoring/goldilocks"
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-gitops
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: system-monitoring-snmp-exporter-cisco-switch
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: system-monitoring-namespace
#   interval: 5m
#   path: "./k8s/clusters/cluster-0/manifests/system-monitoring/snmp-exporter/cisco-switch"
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-monitoring-omada-exporter
  namespace: flux-system
spec:
  dependsOn:
    - name: system-monitoring-namespace
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/system-monitoring/omada-exporter"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-monitoring-opnsense-exporter
  namespace: flux-system
spec:
  dependsOn:
    - name: system-monitoring-namespace
  interval: 5m
  path: "./k8s/clusters/cluster-0/manifests/system-monitoring/opnsense-exporter"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
