apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-nfs-backup
  namespace: database
spec:
  storageClassName: database-nfs-backup
  capacity:
    storage: 40G
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${SECRET_NAS1}
    path: "/mnt/fatguys/Backup/k8s/cnpg"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-nfs-backup
  namespace: database
spec:
  storageClassName: database-nfs-backup
  volumeName: database-nfs-backup
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: database
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: database-nfs-backup
      containers:
      - name: minio
        image: minio/minio:RELEASE.2022-05-19T18-20-59Z
        args:
        - gateway
        - nas
        - /storage
        envFrom:
        - secretRef:
            name: minio-creds
        ports:
        - containerPort: 9000
          hostPort: 9000
        volumeMounts:
        - name: storage
          mountPath: "/storage"
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: database
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minio-creds
  namespace: database
stringData:
  MINIO_ROOT_USER: ${SECRET_CLUSTER_MINIO_ACCESS_KEY}
  MINIO_ROOT_PASSWORD: ${SECRET_CLUSTER_MINIO_SECRET_KEY}
