# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:4U+Kml5D/4sZwPBSgcfgjLb2MD9JndGqVTT9KNnOk9+K6WlhPg==,iv:x6S0tKbYeqY0B2UVg/PjJYYLTj0Z+wCIdpidnIbzpHg=,tag:CGbboLvMlbpmsbnVAsu+Kg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/taylor-cloud/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2022-05-20T04:38:37Z"
          enc: CiQAXmmCQjWnHb6DgAO6NEGwUz6Ft4MKvwrL5ip0WmLTgQRf2hASSQA+M8UojUAhQi0hwTFPVCm4y0OonTUNDhqipcK6S645R5iX8IqyA2w2kklHcHfi0U63CutHhQOGiOUHdfi4PBnugcRSgtiUzRY=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q07mwz002uj9fe262u0uz4xhp2v0jqdppjpald0e259zx3u9yu5sx4klhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMEV0YWJocmNHOWl6VlFJ
            UXFCMVZaY2xKUDd0Ui95WjVWUFpxbEp2QXlJCllzTXVUbmJMaDhjVHlCOWI4eld2
            SmpTVmIwOHN1R0tESWNHT21LWk9JbjgKLS0tIFNaU2RmTXFTdzRTNXViZi9SbkJW
            QjJaaTlCZHVNVmtXVHZwRmJZS0UyMjQKhY0aTVJBIl4gImRoTEZ6Ph/mv+xSFU48
            4JX2/rIGF8/vDnThtJsLwin7RCXqdY8rO04ooAr8RZ9BvIRok91rtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-22T20:55:32Z"
    mac: ENC[AES256_GCM,data:dcUolwyvQeI72IZhcDeYwugfJYLk16BflcTh7MxnzkdEQ59Nzi4usHnQYL5FvOWlz40rDQD1sF6SK+IErxj4rXB+xIkNo0a23T3ncmdXpbs8Znh9h42N0e54wjXj5pqdTKCrtwqldSycnBNnK2nrUbmYpWz0EqMh4Dsy5DYq96c=,iv:QtR57r1sFMx/vgrubk6ovpcNqOaTEEjF7uqLX3e0rag=,tag:ixarfFSoLCU/RARdL/jjag==,type:str]
    pgp:
        - created_at: "2022-05-20T04:38:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwIXOJznC/BzAQ//c253VPdePX+SKQvgwkC/uqaUbN7T30qVHOSs4khs4rWE
            Rl28ZOfCygq/xs7bl7Y9TSPY+QQbLxpE+vXDeQehTHQAh3zmo28a2K7Hi275YHsM
            14woCBMNAkZ/DBiBTqjnBVDLWF8WSRL4G9wqn7LKflt3xXTgwp8BrqBEOXPJPfeS
            7zoHWaN/60wkyHHp1LB9JYyMpQPU992F6nFupeUEvXUwNs+GeTHOtfpUuz8HqHlf
            4jWzOkCWZYKhR8dpl/nT1PKNvX/LK4gJ4EW3Q3RA5Dzf9gtVmmupQQeYZmfIrAQb
            rsd9xhzu/HcUakionJ+MKXA/mRftaJ03wCFkSrZ/94JYhak9fErYHX1fBzDX84me
            ZY8CxJ+tU3MODR5/dz96HXPSzZIIi0QlLsYLMD+8C2UbqoUH3es+UTPHZOyC2bil
            1hFCS92fzJEUycaW6/Z8cy4hgZrKWGPm+bJ/XlYHiUrmsTH2qLMsHfu5WEW19oRR
            MlOcNzndgvKKmmhVAC+wwDy8R/pQIc+lMG16GLWRQ6qTx7hM42Svd2gpgooeQPNa
            9wm26/OXMbJK0AVdZC7A0/WO8PWUZsL6wXwv161sXK5EvGyWiuMQebWE4umZwcK9
            bUGTAeNzKpIMcHLjLBDwAnwNQ46i7VdGeb2DuwkzIRJnqVDkky3dDOUl3P72iLjS
            XgGCA7o8Vf06rKzeLqcur1ROCDlkhpTlJiOxCzGYj6iw57c+HzVyMyIHGxXNMJnD
            hrFVMfZfYqqbG/2QMJzZEP5nOTvbCQa6ZFrJ2ZqiPG10YxJrUMrGRAL96y7qsQw=
            =WEkM
            -----END PGP MESSAGE-----
          fp: 6C9D6C1B579041C3F9A189F9A889A030A843122F
        - created_at: "2022-05-20T04:38:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4gPaNBkmDmPAQ//cvRqFTF7kf1YI2dqBy5UBSAUr5PiRv4jbs70Dog8dPpg
            JAltL2DtYCFXP3UCnL1Nu0g9Ap9V/aAi5DscNnn55C3aYN1xaLxPwP7dHw8IAOoR
            z0C+5E1VGi2O/Uv0MuKmVd7uWhH0dMlJxsy/tmGerLGUhHThIRwqwx9zBbU4GNpZ
            BjX97CEkH2MetrmRA3/ZXrxdcOinTsvkOrdg4hNoGMnGUfw/K5beIaDbNvu0zkhq
            NZG5H8CYHgLaajKqzkkqkqQkXHFYt+yBk/3oohRYmSVLxl07tEPNwi54p4UltR+S
            ONoLjXNvuMgxvERHz4c2kjcaEx+9UX2hxIG+B7RfMSquz9n39Cnb18xea5d9PYkE
            THkJk6u6rp96mqH/qNR8e6M4u2u/amgY7LilyvFkVyx/ZLbzw4j9J7bjt8jB9HXM
            QUhCPjgaTDdDznv6foj+6a7JULq1vJ5i00cqgpgn9ICe3dWIiNHhsVg6HUXV4VTh
            fjXWQJ4pMRkm9iUjRG1eCUi7+JTDapu1RHe7WqEi3eRV7ClQrmBdQMjxk6Hx+YWE
            Yz4EN24BX6Nhv+jeHqwU8UqnVKOxNvG4A1ubbraGQmfjjnCIbYdjVW03hH6Lwx+5
            BQfgBmS2yJ0wTecS1Qs+PsE0neJ+1eK+NdOfgLbogywS+dZYauGWYNYFkwQpbR7S
            XgFYZT0z5vY2WOgUyamsc936F7o8uGyQC2/tjOWBjcAyjsOdWR9smOx8ElHXNAxd
            ImEr5O3axZeoCCkKM7hZEzRyQMzPTjpCq5s5i4/K/qAmgDYwQRrmvjfuz3ZvPXw=
            =dwJb
            -----END PGP MESSAGE-----
          fp: 84EEAB5ACBE82B101D59A1025752228D92EE8D9B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
