---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: convertx-data
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
