---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./zwave.yaml
  - ./coral.yaml
  - ./zigbee.yaml
  - ./intel-gpu-device.yaml
