---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zalando-postgres-pod-secrets
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zalando-postgres-pod-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: ${SECRET_MINIO_ACCESS_KEY}
        AWS_SECRET_ACCESS_KEY: "{{ .minio_zalando_postgres_secret_key }}"
  dataFrom:
    - extract:
        key: minio
