---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kms
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      kms:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/11notes/kms
              tag: 1.0.3@sha256:0eb71bab971959c8e609f280c0e7fe68968cafaab1c066274db12161ffc46674
            env:
              TZ: ${TIMEZONE}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
          ui:
            image:
              repository: ghcr.io/11notes/kms-gui
              tag: 1.0.3@sha256:f3d9365e634fb3f505b6b759c380ce09a6790e615e42a1587c37686fdf7ca1f7
            env:
              TZ: ${TIMEZONE}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "${LB_KMS}"
        ports:
          kms:
            port: 1688
      ui:
        controller: *app
        ports:
          http:
            port: 3000
    ingress:
      app:
        className: "nginx-internal"
        hosts:
          - host: kms-ui.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: ui
                  port: http
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /kms/var
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
