---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vaultwarden-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        ADMIN_TOKEN: "{{ .ADMIN_TOKEN }}"
        DATABASE_URL: postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres.database.svc.cluster.local:5432/vaultwarden
        # Postgres Init
        INIT_POSTGRES_DBNAME: vaultwarden
        INIT_POSTGRES_HOST: postgres.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: vaultwarden
    - extract:
        key: zalandopostgres
