---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: ceph-block

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-nfs-backup
spec:
  storageClassName: audiobookshelf-nfs-backup
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /ook/Backup/k8s/applications/audiobookshelf
    server: ${SECRET_NAS3}
  mountOptions:
    - nfsvers=4.1
    - tcp
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-nfs-backup
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: audiobookshelf-nfs-backup
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-nfs-audiobooks
spec:
  storageClassName: audiobookshelf-nfs-audiobooks
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /ook/Media/books
    server: ${SECRET_NAS3}
  mountOptions:
    - nfsvers=4.1
    - tcp
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-nfs-audiobooks
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: audiobookshelf-nfs-audiobooks
  resources:
    requests:
      storage: 1Mi
