---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ingress-nginx
  namespace: flux-system
spec:
  path: ./k8s/clusters/nas/apps/network/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ingress-nginx
      namespace: network
  interval: 15m
  retryInterval: 1m
  timeout: 2m
