data_dir: /vector-data-dir

api:
  enabled: true
  address: 0.0.0.0:8686

# Sources
sources:
  kubernetes_logs:
    address: 0.0.0.0:6000
    type: vector
    version: "2"

  journal_logs:
    type: vector
    address: 0.0.0.0:6002
    version: "2"

  vector_metrics:
    type: internal_metrics

  talos_kernel_logs:
    address: 0.0.0.0:6050
    type: socket
    mode: udp
    max_length: 102400
    decoding:
      codec: json
    host_key: __host

  talos_service_logs:
    address: 0.0.0.0:6051
    type: socket
    mode: udp
    max_length: 102400
    decoding:
      codec: json
    host_key: __host

# Transformations
transforms:
  # kubernetes_logs_remap:
  #   type: remap
  #   inputs:
  #     - kubernetes_logs
  #   source: |
  #     # Standardize 'app' index
  #     .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || "unknown"
  talos_kernel_logs_xform:
    type: remap
    inputs:
      - talos_kernel_logs
    source: |-
      .__host, err= replace(.__host, "192.168.80.91", "talos-cp-1")
      .__host = replace(.__host, "192.168.80.92", "talos-cp-2")
      .__host = replace(.__host, "192.168.80.90", "physical2")
      # .__host = replace(.__host, "192.168.80.98", "physical1")
      # .__host = replace(.__host, "192.168.80.97", "sff1")
      .__host = replace(.__host, "192.168.80.99", "m720q-1")
  talos_service_logs_xform:
    type: remap
    inputs:
      - talos_service_logs
    source: |-
      .__host, err = replace(.__host, "192.168.80.91", "talos-cp-1")
      .__host = replace(.__host, "192.168.80.92", "talos-cp-2")
      # .__host = replace(.__host, "192.168.80.98", "physical1")
      .__host = replace(.__host, "192.168.80.90", "physical2")
      # .__host = replace(.__host, "192.168.80.97", "sff1")
      .__host = replace(.__host, "192.168.80.99", "m720q-1")

# Sinks
sinks:
  loki_journal:
    type: loki
    inputs:
      - journal_logs
    endpoint: http://loki-gateway:80
    encoding:
      codec: json
    batch:
      max_bytes: 2049000
    out_of_order_action: accept
    remove_label_fields: true
    remove_timestamp: true
    labels:
      hostname: "{{ host }}"
  loki_kubernetes:
    type: loki
    inputs:
      - kubernetes_logs
    endpoint: http://loki-gateway:80
    encoding:
      codec: json
    batch:
      max_bytes: 2049000
    out_of_order_action: rewrite_timestamp
    remove_label_fields: true
    remove_timestamp: true
    labels:
      k8s_app: "{{ custom_app_name }}"
      k8s_container: "{{ kubernetes.container_name }}"
      k8s_filename: "{{ kubernetes.file }}"
      k8s_instance: '{{ kubernetes.pod_labels."app.kubernetes.io/instance" }}'
      k8s_namespace: "{{ kubernetes.pod_namespace }}"
      k8s_node: "{{ kubernetes.pod_node_name }}"
      k8s_pod: "{{ kubernetes.pod_name }}"
  talos_kernel:
    type: loki
    inputs:
      - talos_kernel_logs_xform
    endpoint: http://loki-gateway:80
    encoding:
      codec: json
      except_fields:
        - __host
    batch:
      max_bytes: 1048576
    out_of_order_action: rewrite_timestamp
    labels:
      hostname: "{{ host }}"
      service: "{{ facility }}"
  talos_service:
    type: loki
    inputs:
      - talos_service_logs_xform
    endpoint: http://loki-gateway:80
    encoding:
      codec: json
      except_fields:
        - __host
    batch:
      max_bytes: 524288
    out_of_order_action: rewrite_timestamp
    labels:
      hostname: "{{ host }}"
      service: "talos-service"
      namespace: "talos:service"
