---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-zalando-postgres-secrets
  annotations:
    policies.kyverno.io/title: Sync Zalando Postgres Secrets
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      This policy will copy a Secret called `postgres.postgres.credentials.postgresql.acid.zalan.do` which
      exists in the `database` Namespace to new Namespaces when they are
      created. It will also push updates to the copied Secrets should the
      source Secret be changed.
spec:
  mutateExistingOnPolicyUpdate: true
  generateExistingOnPolicyUpdate: true
  rules:
    - name: sync-zalando-postgres-superuser-secret
      match:
        resources:
          kinds:
            - Namespace
      exclude:
        resources:
          namespaces:
            - database
      generate:
        apiVersion: v1
        kind: Secret
        name: postgres.postgres.credentials.postgresql.acid.zalan.do
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        clone:
          namespace: database
          name: postgres.postgres.credentials.postgresql.acid.zalan.do
